# Generated by Django 3.2.12 on 2023-08-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
