# Generated by Django 3.2.12 on 2023-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20230814_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
