/** @type {import('tailwindcss').Config} */

export default {
  content: [
    //Agregue las rutas
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        principal_2: "url('../src/components/img/principal_2.jpg')",
        principal: "url('../src/components/img/principal.jpg')",
        maquina_E: "url('../src/components/icons/maquina-elevadora.svg')",
        constructor: "url('../src/components/img/constructor.jpg')",
        montacarga: "url('../src/components/img/montacarga_1.jpeg')",
        mantenimiento: "url('../src/components/img/montacarga_3.jpeg')",
        montacarga_2: "url('../src/components/img/montacarga_2.jpg')",
        jungher: "url('../src/components/img/jungher.jpg')",
        portaestiba: "url('../src/components/img/portaestiba_1.jpg')",
        ojoAbierto:"url('../../src/components/img/ojo_abierto.png')",
        ojoCerrado:"url('../../src/components/img/ojos_cerrado.png')",
      },
      backgroundColor: (theme) => ({
        ...theme("colors"),
        primary: "#262626",
        secondary: "#595959",
        tertiary: "#7A8690",
        quaternary: "#828D96",
        quinary: "#89939C",
        senary: "#E0BF7E",
        septenary: "#F9BA4E",
        octonary: "#F4CC66",
        nonary: "#EBEBEB",
      }),
      textColor: {
        primary: "#262626",
        secondary: "#595959",
        tertiary: "#7A8690",
        quaternary: "#828D96",
        quinary: "#89939C",
        senary: "#E0BF7E",
        septenary: "#F9BA4E",
        octonary: "#F4CC66",
        nonary: "#EBEBEB",
      },
      colors: {
        "black-0": "#262626",
        "black-1": "#2b2c32",
        gray: "#595959",
        "gray-light": "#EBEBEB",
        white: "#FCFCFC",
        yellow: "#F4CC66",
        "yellow-2": "#F9BA4E",
        brown: "#E0BF7E",
        blue: "#92a9c3",
        "blue-1": "#89939C",
        "blue-2": "#828D96",
        "blue-3": "#7C90A0",
        'gradient-start': 'rgba(252, 252, 252, 0.2)',
        'gradient-middle': 'rgba(122, 134, 144, 0.4)',
        'gradient-end': 'rgba(120, 151, 176, 0.5)',
      },
      fontFamily: {
        dancing: ["Dancing Script", "cursive"],
        Fuente_primaria: ["Hind Vadodara", "sans-serif"],
        Fuente_secundaria: ["Dancing Script", "cursive"],
        Fuente_terciaria: ["Maitree", "serif"],
      },
    },
  },
};
